on: [push, pull_request]

name: CI

jobs:
  checks:
    name: ${{ matrix.name }} (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    env:
      PROGRAM: ${{ matrix.cross && 'cross' || 'cargo' }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
          - x86_64-unknown-netbsd
          - x86_64-unknown-freebsd
          - aarch64-linux-android
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - aarch64-apple-darwin
          - aarch64-pc-windows-msvc
          - armv7-unknown-linux-gnueabihf

        include:
          - os: ubuntu-latest
            name: GNU/Linux x86_64
            target: x86_64-unknown-linux-gnu
            cross: false
            strip: true

          - os: ubuntu-latest
            name: Linux musl x86_64
            target: x86_64-unknown-linux-musl
            cross: true
            strip: true

          - os: macos-latest
            name: macOS x86_64
            target: x86_64-apple-darwin
            cross: false
            strip: true

          - os: windows-latest
            name: Windows x86_64
            target: x86_64-pc-windows-msvc
            cross: false
            strip: true

          - os: ubuntu-latest
            name: NetBSD x86_64
            target: x86_64-unknown-netbsd
            cross: true
            strip: true

          - os: ubuntu-latest
            name: freeBSD x86_64
            target: x86_64-unknown-freebsd
            cross: true
            strip: true

          - os: ubuntu-latest
            name: Android aarch64
            target: aarch64-linux-android
            cross: true
            strip: true

          - os: ubuntu-latest
            name: GNU/Linux aarch64
            target: aarch64-unknown-linux-gnu
            cross: true
            strip: true

          - os: ubuntu-latest
            name: Linux musl aarch64
            target: aarch64-unknown-linux-musl
            cross: true
            strip: true

          - os: macos-latest
            name: macOS aarch64
            target: aarch64-apple-darwin
            cross: false
            strip: true

          - os: windows-latest
            name: Windows aarch64
            target: aarch64-pc-windows-msvc
            cross: false
            strip: true

          - os: ubuntu-latest
            name: GNU/Linux ARMv7
            target: armv7-unknown-linux-gnueabihf
            cross: true
            strip: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bootstrap
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          targets: ${{ matrix.target }}
      
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
        if: ${{ matrix.cross }}

      - name: Formatting
        run: cargo fmt --all -- --check
        if: ${{ !matrix.cross }}
        continue-on-error: false

      - name: Lints
        run: ${{ env.PROGRAM }} clippy --target=${{ matrix.target }} -- --no-deps -D clippy::all
        continue-on-error: false

      - name: Build
        run: ${{ env.PROGRAM }} build --target=${{ matrix.target }}

      - name: Test
        run: ${{ env.PROGRAM }} test --target=${{ matrix.target }}
        if: ${{ !matrix.cross && !contains(matrix.target, 'aarch64') }}

      - name: Doctor
        run: ${{ env.PROGRAM }} run --target=${{ matrix.target }} -- --doctor
        if: ${{ matrix.test }}
