name: CI

on:
  push:
    - 'src/**'
    - 'vendor/**'
    - 'Cargo.toml'
    - 'Cargo.lock'
  pull_request:
    - 'src/**'
    - 'vendor/**'
    - 'Cargo.toml'
    - 'Cargo.lock'

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Bootstrap
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Formatting
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-targets --all-features

  checks:
    name: ${{ matrix.name }} (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    env:
      PROGRAM: ${{ matrix.cross && 'cross' || 'cargo' }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
          - x86_64-unknown-netbsd
          - x86_64-unknown-freebsd
          - aarch64-linux-android
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - aarch64-apple-darwin
          - aarch64-pc-windows-msvc
          - armv7-unknown-linux-gnueabihf

        include:
          - os: ubuntu-latest
            name: GNU/Linux x86_64
            target: x86_64-unknown-linux-gnu
            cross: false
            test: true

          - os: ubuntu-latest
            name: Linux musl x86_64
            target: x86_64-unknown-linux-musl
            cross: true
            test: true

          - os: macos-latest
            name: macOS x86_64
            target: x86_64-apple-darwin
            cross: false
            test: true

          - os: windows-latest
            name: Windows x86_64
            target: x86_64-pc-windows-msvc
            cross: false
            test: true

          - os: ubuntu-latest
            name: NetBSD x86_64
            target: x86_64-unknown-netbsd
            cross: true
            test: false

          - os: ubuntu-latest
            name: freeBSD x86_64
            target: x86_64-unknown-freebsd
            cross: true
            test: false

          - os: ubuntu-latest
            name: Android aarch64
            target: aarch64-linux-android
            cross: true
            test: true

          - os: ubuntu-latest
            name: GNU/Linux aarch64
            target: aarch64-unknown-linux-gnu
            cross: true
            test: true

          - os: ubuntu-latest
            name: Linux musl aarch64
            target: aarch64-unknown-linux-musl
            cross: true
            test: true

          - os: macos-latest
            name: macOS aarch64
            target: aarch64-apple-darwin
            cross: false
            test: true

          - os: windows-latest
            name: Windows aarch64
            target: aarch64-pc-windows-msvc
            cross: false
            test: false

          - os: ubuntu-latest
            name: GNU/Linux ARMv7
            target: armv7-unknown-linux-gnueabihf
            cross: true
            test: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Bootstrap
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
        if: ${{ matrix.cross }}

      - name: Build
        run: ${{ env.PROGRAM }} build --target=${{ matrix.target }}

      - name: Test
        run: ${{ env.PROGRAM }} test --target=${{ matrix.target }}
        if: ${{ matrix.test }}

      - name: Doctor
        run: ${{ env.PROGRAM }} run --target=${{ matrix.target }} -- --doctor
        if: ${{ !matrix.cross && matrix.test }}
